on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      scope:
        required: true
        type: string
    secrets:
      PAT:
        required: true
      NOTION_INTEGRATION_TOKEN:
        required: false

jobs:
  commit-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Run Gradle
        env:
          NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_INTEGRATION_TOKEN || '' }}
        run: ./gradlew :${{ inputs.scope }}:bootRun

      - name: Debug remote
        run: |
          git remote -v
          echo "PAT length: ${#PAT}"
          echo "PAT hex: $(echo -n $PAT | xxd)"
        env:
          PAT: ${{ secrets.PAT }}

      - name: Commit & Push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global --unset credential.helper || true
          
          git config user.name "William Phan"
          git config user.email "phnam230197@gmail.com"
          
          git add storage/
          git commit \
            -m "chore(${{ inputs.scope }}): ${{ inputs.scope }} Notion JSONs at $(date -u +'%Y-%m-%d %H:%M:%S')" \
            -m "$(git diff --cached --name-status)" \
            || echo "âœ… No changes to commit"
          
          echo "Remote about to add:"
          echo "https://wliamp:${PAT}@github.com/wliamp/notion-storage-${{ inputs.module }}.git" | sed 's/[0-9a-z]\{20,\}/***/g'
          
          git subtree split --prefix storage -b storage-branch
          
          git remote remove storage || true
          git remote add storage "https://wliamp:${PAT}@github.com/wliamp/notion-storage-${{ inputs.module }}.git"
          git remote -v
          
          git push --force storage storage-branch:main
          
          git branch -D storage-branch    
